### PR TITLE
Support three.js > 0.125.0

### LINKED ISSUE #8: Three.js r125 compatibility
image

Three.js r125 removed the `Geometry` class that cannon-es-debugger appears to depend on. I think for the time being it can still be imported [from examples](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/deprecated/Geometry.js).

### PR DESCRIPTION
**Pull request by marcofugaro**
Close #8

Basically rewrite the `createConvexPolyhedronGeometry`, `createTrimeshGeometry` and `createHeightfieldGeometry` to output a `BufferGeometry` instead of a `Geometry`.

### CODE REVIEW

**Comment by stockHuman** [comment]
Well done!

I'm still trying to see about something that _takes_ BufferGeometry and spits out Cannon meshes, at least something that isn't as heavy as importing legacy Geometry, merging vertices, and going that route.

Anyway, I'd merge. This would be a breaking change, no?

**Comment by marcofugaro** [comment]
>  This would be a breaking change, no?

Not at all, BufferGeometry is exported also in previous three versions.

Looking at it now, I'd relax the three peerDepency version to `0.x.x`

**Comment by stockHuman** [comment]
Oh no, I meant that this would no longer support passing the old Geometries in. But I suppose it's silly to still support them.

**Comment by marcofugaro** [comment]
> passing the old Geometries in

I do not understand what you're refering to, the user doesn't pass geometries in this library

**Comment by stockHuman** [comment]
My bad, seems like I was confused as to where this was going. Still, nice.

**Pull request merged**
