### PR TITLE
feat: add support for custom color fn

### LINKED ISSUE #18: Different color for shapes
Saw that in https://github.com/swift502/Sketchbook the physics debugger uses different colors for shapes, thought it was kinda nice. So wondering if it's something we want to add?

### PR DESCRIPTION
**Pull request by alexandernanberg**
Fixes #18 

Example
```js
cannonDebugger(scene, world.bodies, {
  color: (shape) => {
    switch (shape) {
      case CANNON.SHAPE_TYPES.BOX:
      case CANNON.SHAPE_TYPES.CONVEXPOLYHEDRON:
        return 0x0000ff;
      case CANNON.SHAPE_TYPES.TRIMESH:
      case CANNON.SHAPE_TYPES.HEIGHTFIELD:
        return 0xff0000;
      default:
        return 0x00ff00;
    }
  },
});

```

### CODE REVIEW

**Comment by krispya** [comment]
Thanks. I'm not a maintainer, but I tested it out and it works well and is quite useful. If it gets accepted, it would be nice to add support in use-cannon. It works out of the box for color (string, hex, color object) but it will need some work for the ColorFn.

**Comment by codynova** [comment]
Could this be handled with `onInit` instead?

**Comment by alexandernanberg** [comment]
> Could this be handled with onInit instead? 

Possibly, but the API would be harder to get right. Accepting a fn as `color` is clearer IMO

**Comment by codynova** [comment]
I haven't touched the debugger in a long time but I think it would be something along these lines?

```
onInit: (body, mesh, shape) => {
    let color
    switch (shape) {
      case CANNON.SHAPE_TYPES.BOX:
      case CANNON.SHAPE_TYPES.CONVEXPOLYHEDRON:
        color = 0x0000ff;
      case CANNON.SHAPE_TYPES.TRIMESH:
      case CANNON.SHAPE_TYPES.HEIGHTFIELD:
        color = 0xff0000;
      default:
        color = 0x00ff00;
    }
    mesh.color = color
}
```

**Comment by marcofugaro** [comment]
The solution that @codynova posted works and is clean enough. 
There's no need to complicate the debugger even more.

I will close this PR, but thanks for the contribution anyway!

**Comment by alexandernanberg** [comment]
Fair enough

**Pull request closed without merging**
